// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK5kwvTIKiPIR0WvlW8tCzwyYRkls7mdY',
    appId: '1:569262818284:web:3018a2cb3b6e1ef46076c9',
    messagingSenderId: '569262818284',
    projectId: 'thagataxi-bfbd5',
    authDomain: 'thagataxi-bfbd5.firebaseapp.com',
    storageBucket: 'thagataxi-bfbd5.firebasestorage.app',
    measurementId: 'G-BLX2YJ280Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQHLMxxl_51wYOCCu9JDgrbkshfrKtMLM',
    appId: '1:569262818284:android:9a1ab384cf3670876076c9',
    messagingSenderId: '569262818284',
    projectId: 'thagataxi-bfbd5',
    storageBucket: 'thagataxi-bfbd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4tt6YWlGZ_80pI6JndgBIZvvALgnzDHk',
    appId: '1:569262818284:ios:b5f232c0f41e570c6076c9',
    messagingSenderId: '569262818284',
    projectId: 'thagataxi-bfbd5',
    storageBucket: 'thagataxi-bfbd5.firebasestorage.app',
    iosBundleId: 'com.example.thagaTaxi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4tt6YWlGZ_80pI6JndgBIZvvALgnzDHk',
    appId: '1:569262818284:ios:b5f232c0f41e570c6076c9',
    messagingSenderId: '569262818284',
    projectId: 'thagataxi-bfbd5',
    storageBucket: 'thagataxi-bfbd5.firebasestorage.app',
    iosBundleId: 'com.example.thagaTaxi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK5kwvTIKiPIR0WvlW8tCzwyYRkls7mdY',
    appId: '1:569262818284:web:b8d47241f7fb6c816076c9',
    messagingSenderId: '569262818284',
    projectId: 'thagataxi-bfbd5',
    authDomain: 'thagataxi-bfbd5.firebaseapp.com',
    storageBucket: 'thagataxi-bfbd5.firebasestorage.app',
    measurementId: 'G-WEBLN37JCS',
  );
}
